[general]
import = [
    "~/.config/alacritty/themes/themes/blood_moon.toml"
]

[font.normal]
family = "MesloLGS NF"

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }

[window]
opacity = 0.9
